headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Soham Randive\\Desktop\\HydroPINN\\webapp\\static"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=86400"